### PR TITLE
Test log upload

### PR DESCRIPTION
**Pull request by zhanga5**
Signed-off-by: zhanga5 <alex4zhang@gmail.com>

### CODE REVIEW

**Comment by zhanga5** [comment]
build

**Comment by pxLi** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Comment by zhanga5** [comment]
build

**Pull request closed without merging**
